package main

import (
	"github.com/hyperledger/fabric/core/chaincode/shim"
)

var impuestosPrecarga = `[
    {"impuesto":10,"idOrg":1,"nombre":"GANANCIAS SOCIEDADES"},                                                                                        
    {"impuesto":11,"idOrg":1,"nombre":"GANANCIAS PERSONAS FISICAS"},                                                                                  
    {"impuesto":14,"idOrg":1,"nombre":"PRECIOS DE TRANSFERENCIA"},                                                                                    
    {"impuesto":15,"idOrg":1,"nombre":"EMERGENCIA SOBRE ALTAS RENTAS"},                                                                               
    {"impuesto":20,"idOrg":1,"nombre":"MONOTRIBUTO"},                                                                                                 
    {"impuesto":21,"idOrg":1,"nombre":"MONOTRIBUTO AUTONOMO"},                                                                                        
    {"impuesto":22,"idOrg":1,"nombre":"MONOTRIBUTO SEG.SOCIAL"},                                                                                      
    {"impuesto":23,"idOrg":1,"nombre":"MONOTRIBUTO-INTEG.DE SOCIEDAD"},                                                                               
    {"impuesto":25,"idOrg":1,"nombre":"GANANCIA MINIMA PRESUNTA"},                                                                                    
    {"impuesto":26,"idOrg":1,"nombre":"INT.PAG.Y COSTO FINAN.ENDEUDAM"},                                                                              
    {"impuesto":30,"idOrg":1,"nombre":"IVA"},                                                                                                         
    {"impuesto":31,"idOrg":1,"nombre":"RENTAS DIVERSAS"},                                                                                             
    {"impuesto":32,"idOrg":1,"nombre":"IVA EXENTO"},                                                                                                  
    {"impuesto":33,"idOrg":1,"nombre":"IVA RESPONSABLE NO INSCRIPTO"},                                                                                
    {"impuesto":34,"idOrg":1,"nombre":"IVA NO ALCANZADO"},                                                                                            
    {"impuesto":64,"idOrg":1,"nombre":"SICORE-IMPTO.EMERG.AUTOMOTORES"},                                                                              
    {"impuesto":66,"idOrg":1,"nombre":"EXTERIORIZACIÓN - LEY 26.476"},                                                                                
    {"impuesto":72,"idOrg":1,"nombre":"RESP DEUDA AJENA BS.PERS."},                                                                                   
    {"impuesto":73,"idOrg":1,"nombre":"RESP DEUDA AJENA GAN MIN PRES"},                                                                               
    {"impuesto":74,"idOrg":1,"nombre":"F.PAG.RG.896-REG.GRAL."},                                                                                      
    {"impuesto":103,"idOrg":1,"nombre":"REGIMENES DE INFORMACIÓN"},                                                                                   
    {"impuesto":149,"idOrg":1,"nombre":"IMP S/DEB Y CRED EN CTA CTE"},                                                                                
    {"impuesto":154,"idOrg":1,"nombre":"FONDO P/EDUC.Y PROM.COOPTIVA."},                                                                              
    {"impuesto":163,"idOrg":1,"nombre":"EMERGENC.AGROPECUARIA RG.3018"},                                                                              
    {"impuesto":172,"idOrg":1,"nombre":"IMPUESTO TRANSF DE INMUEBLES"},                                                                               
    {"impuesto":180,"idOrg":1,"nombre":"IMPTO.S/BIENES PERSONALES"},                                                                                  
    {"impuesto":181,"idOrg":1,"nombre":"COMB LIQ L 23966 NAFTAS"},                                                                                    
    {"impuesto":186,"idOrg":1,"nombre":"ACTIVOS SOCIEDADES L.23905"},                                                                                 
    {"impuesto":207,"idOrg":1,"nombre":"REG.RET.A LAS GANANCIAS"},                                                                                    
    {"impuesto":208,"idOrg":1,"nombre":"RET.GAN.RG2651-PRE-SICORE"},                                                                                  
    {"impuesto":210,"idOrg":1,"nombre":"GANANCIAS REG ESP INGR RG 830"},                                                                              
    {"impuesto":211,"idOrg":1,"nombre":"BP-ACCIONES O PARTICIPACIONES"},                                                                              
    {"impuesto":212,"idOrg":1,"nombre":"RESP DEUDA AJENA BP - ACC O PA"},                                                                             
    {"impuesto":213,"idOrg":1,"nombre":"REG.RET.A LAS GANANCIAS"},                                                                                    
    {"impuesto":214,"idOrg":1,"nombre":"FONDO SOLIDARIO REDISTRIBUCION"},                                                                             
    {"impuesto":217,"idOrg":1,"nombre":"SICORE-IMPTO.A LAS GANANCIAS"},                                                                               
    {"impuesto":218,"idOrg":1,"nombre":"IMP.A LAS GAN.- BENEF.DEL EXT."},                                                                             
    {"impuesto":219,"idOrg":1,"nombre":"SICORE-IMPTO.S/ BS PERSONALES"},                                                                              
    {"impuesto":229,"idOrg":1,"nombre":"RECARGO SOBRE EL GAS NATURAL"},                                                                               
    {"impuesto":239,"idOrg":1,"nombre":"INTERNOS- AUTOM Y MOTOR GASOIL"},                                                                             
    {"impuesto":241,"idOrg":1,"nombre":"GAS,FONDO HIDRICO DE INFR."},                                                                                 
    {"impuesto":254,"idOrg":1,"nombre":"IVA PRODUCTORES GANADO"},                                                                                     
    {"impuesto":255,"idOrg":1,"nombre":"IVA GANADO BOVINO RG 3125"},                                                                                  
    {"impuesto":256,"idOrg":1,"nombre":"IVA COMPRAVTA GANADO RG3298"},                                                                                
    {"impuesto":257,"idOrg":1,"nombre":"IVA OPER.COMPRA-VENTA FAEN GAN"},                                                                             
    {"impuesto":260,"idOrg":1,"nombre":"IVA C. VTA MAT FAENA GANADO"},                                                                                
    {"impuesto":261,"idOrg":1,"nombre":"IVA USUARIOS FAENA BOVINO "},                                                                                 
    {"impuesto":262,"idOrg":1,"nombre":"IVA ESTABLECIMIENTO FAENADOR"},                                                                               
    {"impuesto":263,"idOrg":1,"nombre":"IVA CONSIGNATARIOS DE HACIENDA"},                                                                             
    {"impuesto":264,"idOrg":1,"nombre":"IVA SUPERMERCADOS"},                                                                                          
    {"impuesto":267,"idOrg":1,"nombre":"IVA ESTAB FAENADOR PORCINO"},                                                                                 
    {"impuesto":268,"idOrg":1,"nombre":"IVA CONSIG HACIENDA PORCINO"},                                                                                
    {"impuesto":269,"idOrg":1,"nombre":"IVA USUARIO FAENA PORCINO"},                                                                                  
    {"impuesto":301,"idOrg":1,"nombre":"EMPLEADOR-APORTES SEG. SOCIAL"},                                                                              
    {"impuesto":304,"idOrg":1,"nombre":"ENTRADAS ESPEC.CINEMATOGRAFICO"},                                                                             
    {"impuesto":305,"idOrg":1,"nombre":"IMPTO. S/VIDEOGRAMA GRABADOS"},                                                                               
    {"impuesto":306,"idOrg":1,"nombre":"IMPTO.S/SERV.RADIODIFUSION TV."},                                                                             
    {"impuesto":307,"idOrg":1,"nombre":"IMPTO.S/RADIODIFUSION AM/FM"},                                                                                
    {"impuesto":308,"idOrg":1,"nombre":"APORTES SEG.SOCIAL AUTONOMOS"},                                                                               
    {"impuesto":313,"idOrg":1,"nombre":"SERV. COMUNICACIÓN AUDIOVISUAL"},                                                                             
    {"impuesto":314,"idOrg":1,"nombre":"SCA ART 96 INC A, D Y/O E."},                                                                                 
    {"impuesto":331,"idOrg":1,"nombre":"REGIMEN DE FACTURACION RG 3419"},                                                                             
    {"impuesto":351,"idOrg":1,"nombre":"CONTRIBUCIONES SEG. SOCIAL"},                                                                                 
    {"impuesto":352,"idOrg":1,"nombre":"CONTRIBUCIONES OBRA SOCIAL"},                                                                                 
    {"impuesto":353,"idOrg":1,"nombre":"RETENCIONES CONTRIB.SEG.SOCIAL"},                                                                             
    {"impuesto":361,"idOrg":1,"nombre":"INTERNOS- TABACOS"},                                                                                          
    {"impuesto":362,"idOrg":1,"nombre":"INTERNOS-ALCOHOLES"},                                                                                         
    {"impuesto":363,"idOrg":1,"nombre":"INTERNOS-BEBIDAS ALCOHOL "},                                                                                  
    {"impuesto":364,"idOrg":1,"nombre":"INTERNOS-VINO CHAMPAGNE "},                                                                                   
    {"impuesto":365,"idOrg":1,"nombre":"INTERNOS-SEGUROS "},                                                                                          
    {"impuesto":366,"idOrg":1,"nombre":"ADICIONAL EMERG.CIGARRILLOS"},                                                                                
    {"impuesto":367,"idOrg":1,"nombre":"INTERNOS-SERV TEL CEL Y SATEL"},                                                                              
    {"impuesto":368,"idOrg":1,"nombre":"INTERNOS-CHAMPAÑAS"},                                                                                         
    {"impuesto":369,"idOrg":1,"nombre":"INTERNOS-VEHIC AUTOM EMBARC"},                                                                                
    {"impuesto":377,"idOrg":1,"nombre":"COM LIQ L.23966/24699 ART 2DOA"},                                                                             
    {"impuesto":395,"idOrg":1,"nombre":"COMB LIQ L 23966/24699 ART 2 B"},                                                                             
    {"impuesto":396,"idOrg":1,"nombre":"COMBUSTIBLES LIQUIDOS IMPORTAD"},                                                                             
    {"impuesto":397,"idOrg":1,"nombre":"COMB LIQ L 23966 GAS LICUADO"},                                                                               
    {"impuesto":398,"idOrg":1,"nombre":"IMPUESTO SOBRE EL GAS OIL, GAS LICUADO Y BIODIESEL"},                                                                               
    {"impuesto":399,"idOrg":1,"nombre":"G.N.C. L.23966"},                                                                                             
    {"impuesto":401,"idOrg":1,"nombre":"MANUF.CIGARRILLOS L.23562"},                                                                                  
    {"impuesto":402,"idOrg":1,"nombre":"INTERNOS-MANUF TABACALES AFIN"},                                                                              
    {"impuesto":405,"idOrg":1,"nombre":"INTERNOS-IMPORT.TABACOS ELABOR"},                                                                             
    {"impuesto":408,"idOrg":1,"nombre":"TABACOS/COMERCIALIZAC.TABACOS"},                                                                              
    {"impuesto":417,"idOrg":1,"nombre":"INTERNOS-DESTIL ALCOHOL INDUST"},                                                                             
    {"impuesto":418,"idOrg":1,"nombre":"INTERNOS-DESTILADOR TANQUES "},                                                                               
    {"impuesto":419,"idOrg":1,"nombre":"INTERNOS-DEST.SUBPR.ALCOH ETIL"},                                                                             
    {"impuesto":420,"idOrg":1,"nombre":"INTERNOS-FRACCION.ALCOHOL ETIL"},                                                                             
    {"impuesto":433,"idOrg":1,"nombre":"ALCOHOLES-MANIP.ALCOHOL ETILIC"},                                                                             
    {"impuesto":434,"idOrg":1,"nombre":"USUARIO ALCOHOL ETILICO"},                                                                                    
    {"impuesto":435,"idOrg":1,"nombre":"MANIPUL ALCOHOL ETILICO"},                                                                                    
    {"impuesto":440,"idOrg":1,"nombre":"ESPECIFICO DE APUESTAS"},                                                                                     
    {"impuesto":442,"idOrg":1,"nombre":"USUARIO ALCOHOL EXENTO"},                                                                                     
    {"impuesto":443,"idOrg":1,"nombre":"I ALCOHOL FAB DESTIL"},                                                                                       
    {"impuesto":444,"idOrg":1,"nombre":"FABRICAC PERFUME A BASE DE ALC"},                                                                             
    {"impuesto":445,"idOrg":1,"nombre":"ALCOHOLES-FRAC.ALCOHOL DESNAT."},                                                                             
    {"impuesto":449,"idOrg":1,"nombre":"INTERNOS-VEHIC. AUTOMOV MOTOR"},                                                                              
    {"impuesto":450,"idOrg":1,"nombre":"INTERNOS-FAB.BEBIDAS ALCOHOLIC"},                                                                             
    {"impuesto":451,"idOrg":1,"nombre":"INTERNOS-CERVEZAS"},                                                                                          
    {"impuesto":453,"idOrg":1,"nombre":"INTERNOS-IMPORT BEBIDA ALCOHOL"},                                                                             
    {"impuesto":454,"idOrg":1,"nombre":"INTERNOS-IMPORT BEB.ALCOH FERM"},                                                                             
    {"impuesto":458,"idOrg":1,"nombre":"GRAV.S/ENERGIA ELECT.LEY 17574"},                                                                             
    {"impuesto":459,"idOrg":1,"nombre":"INTERNOS-CIAS.SEGUROS NACIONAL"},                                                                             
    {"impuesto":461,"idOrg":1,"nombre":"INTERNOS-OTROS BIENES Y SERVIC"},                                                                             
    {"impuesto":462,"idOrg":1,"nombre":"INTERNOS-ACEITES LUBRICANTES"},                                                                               
    {"impuesto":463,"idOrg":1,"nombre":"ADICION.ACEITES LUBRICANTES"},                                                                                
    {"impuesto":466,"idOrg":1,"nombre":"SICORE-PREMIOS JUEGOS Y C.DEP"},                                                                              
    {"impuesto":467,"idOrg":1,"nombre":"INTERNOS-VINOS/BODEGUEROS"},                                                                                  
    {"impuesto":469,"idOrg":1,"nombre":"INTERNOS-FABRIC VINOS POSTRE"},                                                                               
    {"impuesto":471,"idOrg":1,"nombre":"INTERNOS-FABR VINOS ESPUMOSOS"},                                                                              
    {"impuesto":473,"idOrg":1,"nombre":"INTERNOS-FABRICANTES CHAMPAGNE"},                                                                             
    {"impuesto":474,"idOrg":1,"nombre":"INTERNOS-VINOS INTERMEDIARIOS"},                                                                              
    {"impuesto":475,"idOrg":1,"nombre":"INTERNOS-VINOS IMPORTADORES"},                                                                                
    {"impuesto":476,"idOrg":1,"nombre":"INTERNOS-VINOS CORTADORES"},                                                                                  
    {"impuesto":477,"idOrg":1,"nombre":"INTERNOS-VINOS FRACCIONADORES"},                                                                              
    {"impuesto":479,"idOrg":1,"nombre":"INTERNOS-SOBRETASA VINO "},                                                                                   
    {"impuesto":480,"idOrg":1,"nombre":"INTERNOS-ARTICULOS DE TOCADOR"},                                                                              
    {"impuesto":481,"idOrg":1,"nombre":"INTERNOS-OBJETOS SUNTUARIOS"},                                                                                
    {"impuesto":482,"idOrg":1,"nombre":"INTERNOS-CUBIERTAS"},                                                                                         
    {"impuesto":483,"idOrg":1,"nombre":"FONDO NAC.VIALIDAD-CUBIERTAS"},                                                                               
    {"impuesto":484,"idOrg":1,"nombre":"FON.NAC.COMPLEMENT.VIALIDAD"},                                                                                
    {"impuesto":485,"idOrg":1,"nombre":"INTERNOS-BEB.ANALCOHOL JARAB "},                                                                              
    {"impuesto":486,"idOrg":1,"nombre":"GRAV ENERGIA ELECTRICA "},                                                                                    
    {"impuesto":487,"idOrg":1,"nombre":"GRAV PETROLEO CRUDO PROCESADO"},                                                                              
    {"impuesto":489,"idOrg":1,"nombre":"FONDO DE ASIST. A LOS MEDICAM."},                                                                             
    {"impuesto":490,"idOrg":1,"nombre":"GRAV ENERGIA ELECTRICA L 15336"},                                                                             
    {"impuesto":491,"idOrg":1,"nombre":"TRANSF.COMBUSTIBLES LIQUIDOS"},                                                                               
    {"impuesto":494,"idOrg":1,"nombre":"INTERNOS -SERVICIO TELEFONICO"},                                                                              
    {"impuesto":496,"idOrg":1,"nombre":"FONDO.NAC.AUTOPISTAS L.18408"},                                                                               
    {"impuesto":730,"idOrg":1,"nombre":"OPERADORES RG 3569"},                                                                                         
    {"impuesto":731,"idOrg":1,"nombre":"IVA GANADO PORCINO"},                                                                                         
    {"impuesto":738,"idOrg":1,"nombre":"IVA POLLOS PARRILLEROS"},                                                                                     
    {"impuesto":739,"idOrg":1,"nombre":"IVA CAL Y CEMENTO"},                                                                                          
    {"impuesto":760,"idOrg":1,"nombre":"IVA HARINAS Y DERIV DE TRIGO"},                                                                               
    {"impuesto":767,"idOrg":1,"nombre":"SICORE-IMPTO.AL VALOR AGREGADO"},                                                                             
    {"impuesto":787,"idOrg":1,"nombre":"RET ART 79 LEY GCIAS INC A,BYC"},                                                                             
    {"impuesto":967,"idOrg":1,"nombre":"CONV.GREMIAL-AFA"},                                                                                           
    {"impuesto":970,"idOrg":1,"nombre":"CONV.GREMIAL-ALGODONERA"},                                                                                    
    {"impuesto":978,"idOrg":1,"nombre":"CONV.GREMIAL-CEREALERO"},                                                                                     
    {"impuesto":979,"idOrg":1,"nombre":"CONV.DE C.GREMIAL-LANERO"},                                                                                   
    {"impuesto":980,"idOrg":1,"nombre":"CONV.DE C.GREMIAL-TABACALERO"},                                                                               
    {"impuesto":981,"idOrg":1,"nombre":"CONV.DE C.GREMIAL-GANADERO"},                                                                                 
    {"impuesto":982,"idOrg":1,"nombre":"CONV.DE C.GREMIAL-VIÑATERO"},                                                                                 
    {"impuesto":983,"idOrg":1,"nombre":"CONV.GREMIAL-CEREALERO(GRUESA)"},                                                                             
    {"impuesto":984,"idOrg":1,"nombre":"CONV.C.GREMIAL-FORESTAL CHACO"},                                                                              
    {"impuesto":5243,"idOrg":904,"nombre":"INGRESOS BRUTOS CORDOBA"},                                                                                 
    {"impuesto":5244,"idOrg":904,"nombre":"CONTRIBUCION MUNICIPAL"}                                                                         
    ]`

func (s *SmartContract) setInitImpuestos(APIstub shim.ChaincodeStubInterface) Response {
	return s.putParamImpuestos(APIstub, []string{impuestosPrecarga})
}
