package main

import (
	"github.com/hyperledger/fabric/core/chaincode/shim"
)

var impuestosPrecarga = `[
    {"idImpuesto":10,"idOrg":1,"nombre":"GANANCIAS SOCIEDADES"},                                                                                        
    {"idImpuesto":11,"idOrg":1,"nombre":"GANANCIAS PERSONAS FISICAS"},                                                                                  
    {"idImpuesto":14,"idOrg":1,"nombre":"PRECIOS DE TRANSFERENCIA"},                                                                                    
    {"idImpuesto":15,"idOrg":1,"nombre":"EMERGENCIA SOBRE ALTAS RENTAS"},                                                                               
    {"idImpuesto":20,"idOrg":1,"nombre":"MONOTRIBUTO"},                                                                                                 
    {"idImpuesto":21,"idOrg":1,"nombre":"MONOTRIBUTO AUTONOMO"},                                                                                        
    {"idImpuesto":22,"idOrg":1,"nombre":"MONOTRIBUTO SEG.SOCIAL"},                                                                                      
    {"idImpuesto":23,"idOrg":1,"nombre":"MONOTRIBUTO-INTEG.DE SOCIEDAD"},                                                                               
    {"idImpuesto":25,"idOrg":1,"nombre":"GANANCIA MINIMA PRESUNTA"},                                                                                    
    {"idImpuesto":26,"idOrg":1,"nombre":"INT.PAG.Y COSTO FINAN.ENDEUDAM"},                                                                              
    {"idImpuesto":30,"idOrg":1,"nombre":"IVA"},                                                                                                         
    {"idImpuesto":31,"idOrg":1,"nombre":"RENTAS DIVERSAS"},                                                                                             
    {"idImpuesto":32,"idOrg":1,"nombre":"IVA EXENTO"},                                                                                                  
    {"idImpuesto":33,"idOrg":1,"nombre":"IVA RESPONSABLE NO INSCRIPTO"},                                                                                
    {"idImpuesto":34,"idOrg":1,"nombre":"IVA NO ALCANZADO"},                                                                                            
    {"idImpuesto":64,"idOrg":1,"nombre":"SICORE-IMPTO.EMERG.AUTOMOTORES"},                                                                              
    {"idImpuesto":66,"idOrg":1,"nombre":"EXTERIORIZACIÓN - LEY 26.476"},                                                                                
    {"idImpuesto":72,"idOrg":1,"nombre":"RESP DEUDA AJENA BS.PERS."},                                                                                   
    {"idImpuesto":73,"idOrg":1,"nombre":"RESP DEUDA AJENA GAN MIN PRES"},                                                                               
    {"idImpuesto":74,"idOrg":1,"nombre":"F.PAG.RG.896-REG.GRAL."},                                                                                      
    {"idImpuesto":103,"idOrg":1,"nombre":"REGIMENES DE INFORMACIÓN"},                                                                                   
    {"idImpuesto":149,"idOrg":1,"nombre":"IMP S/DEB Y CRED EN CTA CTE"},                                                                                
    {"idImpuesto":154,"idOrg":1,"nombre":"FONDO P/EDUC.Y PROM.COOPTIVA."},                                                                              
    {"idImpuesto":163,"idOrg":1,"nombre":"EMERGENC.AGROPECUARIA RG.3018"},                                                                              
    {"idImpuesto":172,"idOrg":1,"nombre":"IMPUESTO TRANSF DE INMUEBLES"},                                                                               
    {"idImpuesto":180,"idOrg":1,"nombre":"IMPTO.S/BIENES PERSONALES"},                                                                                  
    {"idImpuesto":181,"idOrg":1,"nombre":"COMB LIQ L 23966 NAFTAS"},                                                                                    
    {"idImpuesto":186,"idOrg":1,"nombre":"ACTIVOS SOCIEDADES L.23905"},                                                                                 
    {"idImpuesto":207,"idOrg":1,"nombre":"REG.RET.A LAS GANANCIAS"},                                                                                    
    {"idImpuesto":208,"idOrg":1,"nombre":"RET.GAN.RG2651-PRE-SICORE"},                                                                                  
    {"idImpuesto":210,"idOrg":1,"nombre":"GANANCIAS REG ESP INGR RG 830"},                                                                              
    {"idImpuesto":211,"idOrg":1,"nombre":"BP-ACCIONES O PARTICIPACIONES"},                                                                              
    {"idImpuesto":212,"idOrg":1,"nombre":"RESP DEUDA AJENA BP - ACC O PA"},                                                                             
    {"idImpuesto":213,"idOrg":1,"nombre":"REG.RET.A LAS GANANCIAS"},                                                                                    
    {"idImpuesto":214,"idOrg":1,"nombre":"FONDO SOLIDARIO REDISTRIBUCION"},                                                                             
    {"idImpuesto":217,"idOrg":1,"nombre":"SICORE-IMPTO.A LAS GANANCIAS"},                                                                               
    {"idImpuesto":218,"idOrg":1,"nombre":"IMP.A LAS GAN.- BENEF.DEL EXT."},                                                                             
    {"idImpuesto":219,"idOrg":1,"nombre":"SICORE-IMPTO.S/ BS PERSONALES"},                                                                              
    {"idImpuesto":229,"idOrg":1,"nombre":"RECARGO SOBRE EL GAS NATURAL"},                                                                               
    {"idImpuesto":239,"idOrg":1,"nombre":"INTERNOS- AUTOM Y MOTOR GASOIL"},                                                                             
    {"idImpuesto":241,"idOrg":1,"nombre":"GAS,FONDO HIDRICO DE INFR."},                                                                                 
    {"idImpuesto":254,"idOrg":1,"nombre":"IVA PRODUCTORES GANADO"},                                                                                     
    {"idImpuesto":255,"idOrg":1,"nombre":"IVA GANADO BOVINO RG 3125"},                                                                                  
    {"idImpuesto":256,"idOrg":1,"nombre":"IVA COMPRAVTA GANADO RG3298"},                                                                                
    {"idImpuesto":257,"idOrg":1,"nombre":"IVA OPER.COMPRA-VENTA FAEN GAN"},                                                                             
    {"idImpuesto":260,"idOrg":1,"nombre":"IVA C. VTA MAT FAENA GANADO"},                                                                                
    {"idImpuesto":261,"idOrg":1,"nombre":"IVA USUARIOS FAENA BOVINO "},                                                                                 
    {"idImpuesto":262,"idOrg":1,"nombre":"IVA ESTABLECIMIENTO FAENADOR"},                                                                               
    {"idImpuesto":263,"idOrg":1,"nombre":"IVA CONSIGNATARIOS DE HACIENDA"},                                                                             
    {"idImpuesto":264,"idOrg":1,"nombre":"IVA SUPERMERCADOS"},                                                                                          
    {"idImpuesto":267,"idOrg":1,"nombre":"IVA ESTAB FAENADOR PORCINO"},                                                                                 
    {"idImpuesto":268,"idOrg":1,"nombre":"IVA CONSIG HACIENDA PORCINO"},                                                                                
    {"idImpuesto":269,"idOrg":1,"nombre":"IVA USUARIO FAENA PORCINO"},                                                                                  
    {"idImpuesto":301,"idOrg":1,"nombre":"EMPLEADOR-APORTES SEG. SOCIAL"},                                                                              
    {"idImpuesto":304,"idOrg":1,"nombre":"ENTRADAS ESPEC.CINEMATOGRAFICO"},                                                                             
    {"idImpuesto":305,"idOrg":1,"nombre":"IMPTO. S/VIDEOGRAMA GRABADOS"},                                                                               
    {"idImpuesto":306,"idOrg":1,"nombre":"IMPTO.S/SERV.RADIODIFUSION TV."},                                                                             
    {"idImpuesto":307,"idOrg":1,"nombre":"IMPTO.S/RADIODIFUSION AM/FM"},                                                                                
    {"idImpuesto":308,"idOrg":1,"nombre":"APORTES SEG.SOCIAL AUTONOMOS"},                                                                               
    {"idImpuesto":313,"idOrg":1,"nombre":"SERV. COMUNICACIÓN AUDIOVISUAL"},                                                                             
    {"idImpuesto":314,"idOrg":1,"nombre":"SCA ART 96 INC A, D Y/O E."},                                                                                 
    {"idImpuesto":331,"idOrg":1,"nombre":"REGIMEN DE FACTURACION RG 3419"},                                                                             
    {"idImpuesto":351,"idOrg":1,"nombre":"CONTRIBUCIONES SEG. SOCIAL"},                                                                                 
    {"idImpuesto":352,"idOrg":1,"nombre":"CONTRIBUCIONES OBRA SOCIAL"},                                                                                 
    {"idImpuesto":353,"idOrg":1,"nombre":"RETENCIONES CONTRIB.SEG.SOCIAL"},                                                                             
    {"idImpuesto":361,"idOrg":1,"nombre":"INTERNOS- TABACOS"},                                                                                          
    {"idImpuesto":362,"idOrg":1,"nombre":"INTERNOS-ALCOHOLES"},                                                                                         
    {"idImpuesto":363,"idOrg":1,"nombre":"INTERNOS-BEBIDAS ALCOHOL "},                                                                                  
    {"idImpuesto":364,"idOrg":1,"nombre":"INTERNOS-VINO CHAMPAGNE "},                                                                                   
    {"idImpuesto":365,"idOrg":1,"nombre":"INTERNOS-SEGUROS "},                                                                                          
    {"idImpuesto":366,"idOrg":1,"nombre":"ADICIONAL EMERG.CIGARRILLOS"},                                                                                
    {"idImpuesto":367,"idOrg":1,"nombre":"INTERNOS-SERV TEL CEL Y SATEL"},                                                                              
    {"idImpuesto":368,"idOrg":1,"nombre":"INTERNOS-CHAMPAÑAS"},                                                                                         
    {"idImpuesto":369,"idOrg":1,"nombre":"INTERNOS-VEHIC AUTOM EMBARC"},                                                                                
    {"idImpuesto":377,"idOrg":1,"nombre":"COM LIQ L.23966/24699 ART 2DOA"},                                                                             
    {"idImpuesto":395,"idOrg":1,"nombre":"COMB LIQ L 23966/24699 ART 2 B"},                                                                             
    {"idImpuesto":396,"idOrg":1,"nombre":"COMBUSTIBLES LIQUIDOS IMPORTAD"},                                                                             
    {"idImpuesto":397,"idOrg":1,"nombre":"COMB LIQ L 23966 GAS LICUADO"},                                                                               
    {"idImpuesto":398,"idOrg":1,"nombre":"IMPUESTO SOBRE EL GAS OIL, GAS LICUADO Y BIODIESEL"},                                                                               
    {"idImpuesto":399,"idOrg":1,"nombre":"G.N.C. L.23966"},                                                                                             
    {"idImpuesto":401,"idOrg":1,"nombre":"MANUF.CIGARRILLOS L.23562"},                                                                                  
    {"idImpuesto":402,"idOrg":1,"nombre":"INTERNOS-MANUF TABACALES AFIN"},                                                                              
    {"idImpuesto":405,"idOrg":1,"nombre":"INTERNOS-IMPORT.TABACOS ELABOR"},                                                                             
    {"idImpuesto":408,"idOrg":1,"nombre":"TABACOS/COMERCIALIZAC.TABACOS"},                                                                              
    {"idImpuesto":417,"idOrg":1,"nombre":"INTERNOS-DESTIL ALCOHOL INDUST"},                                                                             
    {"idImpuesto":418,"idOrg":1,"nombre":"INTERNOS-DESTILADOR TANQUES "},                                                                               
    {"idImpuesto":419,"idOrg":1,"nombre":"INTERNOS-DEST.SUBPR.ALCOH ETIL"},                                                                             
    {"idImpuesto":420,"idOrg":1,"nombre":"INTERNOS-FRACCION.ALCOHOL ETIL"},                                                                             
    {"idImpuesto":433,"idOrg":1,"nombre":"ALCOHOLES-MANIP.ALCOHOL ETILIC"},                                                                             
    {"idImpuesto":434,"idOrg":1,"nombre":"USUARIO ALCOHOL ETILICO"},                                                                                    
    {"idImpuesto":435,"idOrg":1,"nombre":"MANIPUL ALCOHOL ETILICO"},                                                                                    
    {"idImpuesto":440,"idOrg":1,"nombre":"ESPECIFICO DE APUESTAS"},                                                                                     
    {"idImpuesto":442,"idOrg":1,"nombre":"USUARIO ALCOHOL EXENTO"},                                                                                     
    {"idImpuesto":443,"idOrg":1,"nombre":"I ALCOHOL FAB DESTIL"},                                                                                       
    {"idImpuesto":444,"idOrg":1,"nombre":"FABRICAC PERFUME A BASE DE ALC"},                                                                             
    {"idImpuesto":445,"idOrg":1,"nombre":"ALCOHOLES-FRAC.ALCOHOL DESNAT."},                                                                             
    {"idImpuesto":449,"idOrg":1,"nombre":"INTERNOS-VEHIC. AUTOMOV MOTOR"},                                                                              
    {"idImpuesto":450,"idOrg":1,"nombre":"INTERNOS-FAB.BEBIDAS ALCOHOLIC"},                                                                             
    {"idImpuesto":451,"idOrg":1,"nombre":"INTERNOS-CERVEZAS"},                                                                                          
    {"idImpuesto":453,"idOrg":1,"nombre":"INTERNOS-IMPORT BEBIDA ALCOHOL"},                                                                             
    {"idImpuesto":454,"idOrg":1,"nombre":"INTERNOS-IMPORT BEB.ALCOH FERM"},                                                                             
    {"idImpuesto":458,"idOrg":1,"nombre":"GRAV.S/ENERGIA ELECT.LEY 17574"},                                                                             
    {"idImpuesto":459,"idOrg":1,"nombre":"INTERNOS-CIAS.SEGUROS NACIONAL"},                                                                             
    {"idImpuesto":461,"idOrg":1,"nombre":"INTERNOS-OTROS BIENES Y SERVIC"},                                                                             
    {"idImpuesto":462,"idOrg":1,"nombre":"INTERNOS-ACEITES LUBRICANTES"},                                                                               
    {"idImpuesto":463,"idOrg":1,"nombre":"ADICION.ACEITES LUBRICANTES"},                                                                                
    {"idImpuesto":466,"idOrg":1,"nombre":"SICORE-PREMIOS JUEGOS Y C.DEP"},                                                                              
    {"idImpuesto":467,"idOrg":1,"nombre":"INTERNOS-VINOS/BODEGUEROS"},                                                                                  
    {"idImpuesto":469,"idOrg":1,"nombre":"INTERNOS-FABRIC VINOS POSTRE"},                                                                               
    {"idImpuesto":471,"idOrg":1,"nombre":"INTERNOS-FABR VINOS ESPUMOSOS"},                                                                              
    {"idImpuesto":473,"idOrg":1,"nombre":"INTERNOS-FABRICANTES CHAMPAGNE"},                                                                             
    {"idImpuesto":474,"idOrg":1,"nombre":"INTERNOS-VINOS INTERMEDIARIOS"},                                                                              
    {"idImpuesto":475,"idOrg":1,"nombre":"INTERNOS-VINOS IMPORTADORES"},                                                                                
    {"idImpuesto":476,"idOrg":1,"nombre":"INTERNOS-VINOS CORTADORES"},                                                                                  
    {"idImpuesto":477,"idOrg":1,"nombre":"INTERNOS-VINOS FRACCIONADORES"},                                                                              
    {"idImpuesto":479,"idOrg":1,"nombre":"INTERNOS-SOBRETASA VINO "},                                                                                   
    {"idImpuesto":480,"idOrg":1,"nombre":"INTERNOS-ARTICULOS DE TOCADOR"},                                                                              
    {"idImpuesto":481,"idOrg":1,"nombre":"INTERNOS-OBJETOS SUNTUARIOS"},                                                                                
    {"idImpuesto":482,"idOrg":1,"nombre":"INTERNOS-CUBIERTAS"},                                                                                         
    {"idImpuesto":483,"idOrg":1,"nombre":"FONDO NAC.VIALIDAD-CUBIERTAS"},                                                                               
    {"idImpuesto":484,"idOrg":1,"nombre":"FON.NAC.COMPLEMENT.VIALIDAD"},                                                                                
    {"idImpuesto":485,"idOrg":1,"nombre":"INTERNOS-BEB.ANALCOHOL JARAB "},                                                                              
    {"idImpuesto":486,"idOrg":1,"nombre":"GRAV ENERGIA ELECTRICA "},                                                                                    
    {"idImpuesto":487,"idOrg":1,"nombre":"GRAV PETROLEO CRUDO PROCESADO"},                                                                              
    {"idImpuesto":489,"idOrg":1,"nombre":"FONDO DE ASIST. A LOS MEDICAM."},                                                                             
    {"idImpuesto":490,"idOrg":1,"nombre":"GRAV ENERGIA ELECTRICA L 15336"},                                                                             
    {"idImpuesto":491,"idOrg":1,"nombre":"TRANSF.COMBUSTIBLES LIQUIDOS"},                                                                               
    {"idImpuesto":494,"idOrg":1,"nombre":"INTERNOS -SERVICIO TELEFONICO"},                                                                              
    {"idImpuesto":496,"idOrg":1,"nombre":"FONDO.NAC.AUTOPISTAS L.18408"},                                                                               
    {"idImpuesto":730,"idOrg":1,"nombre":"OPERADORES RG 3569"},                                                                                         
    {"idImpuesto":731,"idOrg":1,"nombre":"IVA GANADO PORCINO"},                                                                                         
    {"idImpuesto":738,"idOrg":1,"nombre":"IVA POLLOS PARRILLEROS"},                                                                                     
    {"idImpuesto":739,"idOrg":1,"nombre":"IVA CAL Y CEMENTO"},                                                                                          
    {"idImpuesto":760,"idOrg":1,"nombre":"IVA HARINAS Y DERIV DE TRIGO"},                                                                               
    {"idImpuesto":767,"idOrg":1,"nombre":"SICORE-IMPTO.AL VALOR AGREGADO"},                                                                             
    {"idImpuesto":787,"idOrg":1,"nombre":"RET ART 79 LEY GCIAS INC A,BYC"},                                                                             
    {"idImpuesto":967,"idOrg":1,"nombre":"CONV.GREMIAL-AFA"},                                                                                           
    {"idImpuesto":970,"idOrg":1,"nombre":"CONV.GREMIAL-ALGODONERA"},                                                                                    
    {"idImpuesto":978,"idOrg":1,"nombre":"CONV.GREMIAL-CEREALERO"},                                                                                     
    {"idImpuesto":979,"idOrg":1,"nombre":"CONV.DE C.GREMIAL-LANERO"},                                                                                   
    {"idImpuesto":980,"idOrg":1,"nombre":"CONV.DE C.GREMIAL-TABACALERO"},                                                                               
    {"idImpuesto":981,"idOrg":1,"nombre":"CONV.DE C.GREMIAL-GANADERO"},                                                                                 
    {"idImpuesto":982,"idOrg":1,"nombre":"CONV.DE C.GREMIAL-VIÑATERO"},                                                                                 
    {"idImpuesto":983,"idOrg":1,"nombre":"CONV.GREMIAL-CEREALERO(GRUESA)"},                                                                             
    {"idImpuesto":984,"idOrg":1,"nombre":"CONV.C.GREMIAL-FORESTAL CHACO"},                                                                              
    {"idImpuesto":5243,"idOrg":904,"nombre":"INGRESOS BRUTOS CORDOBA"},                                                                                 
    {"idImpuesto":5244,"idOrg":904,"nombre":"CONTRIBUCION MUNICIPAL"}                                                                         
    ]`

func (s *SmartContract) setInitImpuestos(APIstub shim.ChaincodeStubInterface) Response {
	return s.putParamImpuestos(APIstub, []string{impuestosPrecarga})
}
